### ISSUE TITLE
svchost/discosvchost/disco/oauth_client.go:160:10: undefined: strings.Builder

### ISSUE THREAD

**Issue by jgspratt** [hashicorp/terraform#22578]
I believe this stopped working with the release of 12.7.  It was last known good on Aug 16 and stable before that.

### Terraform Version

```
12.7
```

### Crash Output

```
# go install ./tools/terraform-bundle
# github.com/hashicorp/terraform/svchost/disco
svchost/disco/oauth_client.go:160:10: undefined: strings.Builder
```

### Expected Behavior

`terraform-bundle` should build (like it did previously)

### Actual Behavior

```
# go install ./tools/terraform-bundle
# github.com/hashicorp/terraform/svchost/disco
svchost/disco/oauth_client.go:160:10: undefined: strings.Builder
```

### Steps to Reproduce

First get terraform and go-getter source in your preferred way, then:

```
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
cd /root/go/src/github.com/hashicorp/terraform/
go install ./tools/terraform-bundle
```

**Comment by teamterraform** [comment]
Hi @jgspratt,

That error indicates you're using an out of date version of Go. The current version of Go at this time is `go1.12.9`.

You should generally use the latest stable release of Go. Terraform also heavily uses Go modules, and may require the use of modules when building some packages.

**Comment by jgspratt** [comment]
The latest available in AWS Linux 2's `@amzn2-core` repo is `1.9.4-3.amzn2.0.1`
