### ISSUE TITLE
provider/azure: SDK introduced a breaking change

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#4461]
Azure tests are failing:
```
# github.com/hashicorp/terraform/builtin/providers/azure
builtin/providers/azure/resource_azure_instance.go:698: undefined: vmutils.ConfigureDeploymentFromVMImage
```
which I believe is caused by https://github.com/Azure/azure-sdk-for-go/pull/253

I don't have enough knowledge about Azure to fix this, in fact I'm thinking the fix may not be as trivial as replacing one method name with another, but actually adding some logic (or even DSL attributes?) for handling user/public VM images.

**Comment by radeksimko** [comment]
fixed via https://github.com/hashicorp/terraform/pull/4467
