### ISSUE TITLE
0.12 SDK / Test Runner can't use exclusively aliased provider

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform#20735]
### Terraform Version

```
Vendored 247faca59d9d (0.12, master a few days ago) into the `google-beta` provider
```

### Terraform Configuration Files
https://github.com/terraform-providers/terraform-provider-google-beta/blob/master/google-beta/resource_compute_managed_ssl_certificate_generated_test.go

Also relevant:

https://github.com/terraform-providers/terraform-provider-google-beta/blob/master/google-beta/provider_test.go#L69-L76

### Expected Behavior
The test runs to completion, as it does in 0.11

### Actual Behavior
```
        Error: Error initializing context: 2 problems:
        
        - Could not satisfy plugin requirements: 
        Plugin reinitialization required. Please run "terraform init".
        
        Plugins are external binaries that Terraform uses to access and manipulate
        resources. The configuration provided requires plugins which can't be located,
        don't satisfy the version constraints, or are otherwise incompatible.
        
        Terraform automatically discovers provider requirements from your
        configuration, including providers used in child modules. To see the
        requirements and constraints from each module, run "terraform providers".
        
        - provider "google" is not available
```

### Steps to Reproduce
Running `TestAccComputeManagedSslCertificate_managedSslCertificateBasicExample`

### Additional Context
We use the aliased provider to make sure that the content of the test will work with live Terraform; this worked in `0.11`, but I guess something has changed in `0.12`.

We'd strongly prefer a solution that doesn't involve also adding the `google` provider for these tests; we want to ensure the alias is used for every resource, since inside the `google-beta` tests the `google` provider *is* `google-beta`, confusingly, and configs could be incorrect.

**Comment by apparentlymart** [comment]
Thanks for reporting this, @rileykarson.

It looks like the logic that builds the required provider set is incorrectly detecting that the `google` provider is required even though there's no explicit reference to it. If I've understood that correctly, I expect that this would also result in `terraform init` trying to install the `google` provider even though a configuration might use only the `google-beta` provider.

The provider dependency detection logic lives in Terraform Core, but I've also labelled this as `provider-sdk` since as we can see here in practice this logic also runs as part of the SDK test harness when preparing to run the Terraform operations, and so we must make sure that the way the test harness runs Terraform in the latest version is correct to get the desired result in this scenario.

**Comment by apparentlymart** [comment]
In my local testing it looks like the problem arises only at the final destroy step of the test:

```
--- FAIL: TestAccComputeManagedSslCertificate_managedSslCertificateBasicExample (26.74s)
    testing.go:629: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.
        
        Error: Error initializing context: 2 problems:
        
        - Could not satisfy plugin requirements: 
        Plugin reinitialization required. Please run "terraform init".
        
        Plugins are external binaries that Terraform uses to access and manipulate
        resources. The configuration provided requires plugins which can't be located,
        don't satisfy the version constraints, or are otherwise incompatible.
        
        Terraform automatically discovers provider requirements from your
        configuration, including providers used in child modules. To see the
        requirements and constraints from each module, run "terraform providers".
        
        - provider "google" is not available
```

This suggests that it's something in the _state_ that is causing this errant extra dependency. I'm going to dig further to see if I can figure out exactly what about the state (or the logic for extracting dependencies from it) is incorrect here.

**Comment by apparentlymart** [comment]
Okay I think I've figured out the root problem here, and fortunately it's within the test harness itself, not within Terraform:

We're still using a mostly-unmodified test harness that was originally written around the 0.11 APIs, so before and after each test step there are shimming steps to convert back and forth between the old and new state models. It seems that the shim out (from new to old) is dropping the record of which provider config each resource belongs to, which is then triggering some backward-compatibility behavior when shimming the other way (from old to new) where the provider address gets defaulted based on the resource type name, which starts with `google_` here.

It looks like the fix will be to fix the shims to ensure that the provider addresses are preserved as we move between the two model types, thus allowing the final destroy step to see correctly that these resources in state all belong to the `google-beta` provider.
